{
	"appId": "btg_test_app",
	"applicationName": "BTG Test App iOS",
	"ariaEnabled": true,
	"nielsenEnabled": true,
	"nielsenAppID": "T383342AD-ACC2-4BFA-86A1-2CA4ECB932F6",
	"nielsenSFCode": "uat-cert",
	"loggingEnabled": true,
	"admsMeasureEnabled": true,
	"admsSslEnabled": false,
	"admsDebugLoggingEnabled": true,
	"omnitureTimeSpentTrackingEnabled": false,
	"admsOfflineTrackingEnabled": false,
	"audienceManagerEnabled": false,
	"admsLifecycleSessionTimeout": 300,
	"admsOfflineHitLimit": 1000,
	"admsReportSuiteIDs": "viarnd",
	"admsTrackingServer": "sc.mtv.com",
	"admsVisitorID": "",
	"admsCharacterSet": "ISO-8859-1",
	"admsCurrencyCode": "USD",
	"omnitureVarMap": {
		"xrs": "campaign"
	},
	"comScoreEnabled": true,
	"comScorePrimaryID": "6036034",
	"comScorePublisherSecret": "674879b3e61bb0264a49c40226ed442b",
	"demdexEnabled": true,
	"loggingEnabled": true,
	"tveEnabled": true,
	"isCoppaCompliant": false,
	"tveContextData": {},
	"admsContextData": {},
	"version": "2.1.0",
	"TTL": 0
}